### ISSUE TITLE
no codes for HACR, ICPCR in ICASA

### ISSUE THREAD

**Issue by chporter** [agmip/VMapper#34]
This is an issue with ICASA, but we have to figure out how to implement a solution that works for VMapper and other AgMIP software.

Variables CRID, HACR, and ICPCR are all associated with crop codes, but only CRID is mapped to crop codes in ICASA. How do we  create the same codes and have the software recognize them?

**Comment by frostbytten** [comment]
Yes, this should be handled in ace-core
________________________________

**Comment by chporter** [comment]
@frostbytten Should we include the other two variable names in column A of the Crop_codes sheet?

**Comment by MengZhang** [comment]
> @frostbytten Should we include the other two variable names in column A of the Crop_codes sheet?

I think this should be the correct way for expressing it in ICASA
