### ISSUE TITLE
Configuration should include mount point on server

### ISSUE THREAD

**Issue by frostbytten** [agmip/VMapper#37]
All URLs are relative to the root of the server (data.agmip.org for example) vs to the mount point (data.agmip.org/tools/vmapper) and cannot load resources. This causes all Javascript to fail.

**Comment by MengZhang** [comment]
@frostbytten 
I will add the following path config,
URL_ROOT=/

let me know if that works for you

**Comment by frostbytten** [comment]
What do the index and resource do? They might be the solution.
________________________________

**Comment by MengZhang** [comment]
I have simplified the config to one parameter for this purpose as I edited my original reply. For your case, i suppose it should be
URL_ROOT=/tools/vmapper/

**Comment by frostbytten** [comment]
Unfortunately, there are some major issues with the redirection. 

with URL_ROOT=/tools/

`/tools/index` works `/tools/vmapper` doesn't but `/tools/tools/vmapper` does. The Javascript files are still not found.
